CREATE TABLE IF NOT EXISTS footer_social_links (
    id INT(11) NOT NULL AUTO_INCREMENT,
    platform VARCHAR(100) NOT NULL,
    icon_class VARCHAR(150) DEFAULT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT(11) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_uca1400_ai_ci;
